### ISSUE TITLE
academic integrity

### ISSUE THREAD

**Issue by gelisam** [dimecon/free-cats#2]
@dimecon said:

> One thing I'm worried about is academic integrity. I need to ask my instructor if it is alright that my project is helping you with your category-syntax project. If it isn't alright (it should be), I'd still like to help you with it. I'm also curious as to what your thoughts are about this.

**Comment by gelisam** [comment]
Hmm, I'd be more worried about whether it's all right that I help and guide you on work that you're supposed to do on your own in exchange for grades, than about whether it's all right that you're helping me on work for which I neither get money nor grades.

**Comment by dimecon** [comment]
Yeah, that's what I was worried about. I'm going to work on a different project for the course, but also continue working on this with you.

**Comment by gelisam** [comment]
As you wish! It will change the dynamic quite a bit though. I was planning to guide you through increasingly-difficult proofs until the end of your course, hoping that by that time we'd be sufficiently far along that you'd have something interesting to show for your course, and sufficiently close to my goal that building on top of what you wrote would be helpful for me. But if there's no fixed end date and you don't get credits for the work, then I don't think it makes sense for you to do all the work while I guide you along. How about this new dynamic instead: we're both working on a common open source Agda project, we both contribute code, and instead of giving you exercises we divide up the work according to our abilities and interests. Sounds good?

**Comment by dimecon** [comment]
Sounds good, as long as you leave enough work for me! I don't see why you can't still guide me and give me exercises, though, unless you don't want to do that. How would you you like to divide up the work?

**Comment by gelisam** [comment]
> I don't see why you can't still guide me and give me exercises

If that's what you prefer, I guess we can do that too! Okay, I'll continue giving you exercises until you get bored, until you get too busy with other things, or until we complete the entire thing.
