### ISSUE TITLE
Simplifying soundness proof for the free monoid representation

### ISSUE THREAD

**Issue by dimecon** [dimecon/free-cats#6]
So I free monoid representation proof, but I think it's redundant. I couldn't quite figure out how to remove these redundancies without running into problems with the termination checker. Do you have any advice?

I also feel like this is way more complicated than it needs to be.

```
    sound : {e e' : ExpMonoid}
          → mon→list e ≡ mon→list e'
          → EquivMonoid e e'
    sound {MEmpty} {MEmpty} _ = equiv-refl
    sound {MEmpty} {Embed x} ()
    sound {MEmpty} {e <> e'} prf = begin⟨ equiv-setoid ⟩
      MEmpty
        ≈⟨ equiv-refl ⟩
      list→mon []
        ≈⟨ resp-≡ prf ⟩
      list→mon (mon→list e ++ mon→list e')
        ≈⟨ resp-++ ⟩
      list→mon (mon→list e) <> list→mon (mon→list e')
        ≈⟨ equiv-cong list→mon-inv list→mon-inv ⟩
      (e <> e') ∎
    sound {e <> e'} {Embed x} prf = begin⟨ equiv-setoid ⟩
      (e <> e')
        ≈⟨ equiv-cong (equiv-sym list→mon-inv) (equiv-sym list→mon-inv) ⟩
      (list→mon (mon→list e) <> list→mon (mon→list e'))
        ≈⟨ equiv-sym resp-++ ⟩
      list→mon (mon→list e ++ mon→list e')
        ≈⟨ resp-≡ prf ⟩
      list→mon (x ∷ [])
        ≈⟨ equiv-refl ⟩
      ((Embed x) <> MEmpty)
        ≈⟨ right-id-mempty ⟩
      Embed x ∎
    sound {e₁ <> e₂} {e₁' <> e₂'} prf = begin⟨ equiv-setoid ⟩
      (e₁ <> e₂)
        ≈⟨ equiv-sym list→mon-inv ⟩
      list→mon (mon→list (e₁ <> e₂))
        ≈⟨ resp-≡ refl ⟩
      list→mon (mon→list e₁ ++ mon→list e₂)
        ≈⟨ resp-≡ prf ⟩
      list→mon (mon→list e₁' ++ mon→list e₂')
        ≈⟨ resp-++ ⟩
      (list→mon (mon→list e₁') <> list→mon (mon→list e₂'))
        ≈⟨ equiv-cong list→mon-inv list→mon-inv ⟩
      (e₁' <> e₂') ∎
    sound {e <> e'} {MEmpty} prf = begin⟨ equiv-setoid ⟩
      (e <> e')
        ≈⟨ equiv-cong (equiv-sym list→mon-inv) (equiv-sym list→mon-inv) ⟩
      list→mon (mon→list e) <> list→mon (mon→list e')
        ≈⟨ equiv-sym resp-++ ⟩
      list→mon (mon→list e ++ mon→list e')
        ≈⟨ resp-≡ prf ⟩
      list→mon []
        ≈⟨ equiv-refl ⟩
      MEmpty ∎
    sound {Embed x} {Embed .x} refl = equiv-refl
    sound {Embed x} {MEmpty} ()
    sound {Embed x} {e <> e'} prf = begin⟨ equiv-setoid ⟩
      Embed x
        ≈⟨ equiv-sym right-id-mempty ⟩
      list→mon (x ∷ [])
        ≈⟨ resp-≡ prf ⟩
      list→mon (mon→list e ++ mon→list e')
        ≈⟨ resp-++ ⟩
      (list→mon (mon→list e) <> list→mon (mon→list e'))
        ≈⟨ equiv-cong list→mon-inv list→mon-inv ⟩
(e <> e') ∎
```

For example, I tried to do the `sound {Embed x} {e <> e'}` proof recursively in terms of the completed `sound {e <> e'} {Embed x}` proof, but then Agda complains about termination.

**Comment by gelisam** [comment]
My proof is actually longer, but it is split into a few lemmas and each of them is quite short. I don't know if you like that better, but here's what I did anyway:
1. I defined `list→mon` to convert a list into an ExpMonoid with the same shape as the list.
2. I proved that `list→mon` preserves `mempty` and `mappend`.
3. I used (2) to prove that every ExpMonoid is equivalent to the `list→mon` of its `mon→list`.
4. I proved soundness by using (3) to show that both sides are equivalent to the same `list→mon`'d list.

**Comment by gelisam** [comment]
Now that I'm taking a closer look, I see that you did (1) (2) and (3) as well, so my proof is just (4) and it is indeed much shorter.

**Comment by dimecon** [comment]
> and it is indeed much shorter.

After your closer look, do you mean that yours is much shorter?

**Comment by gelisam** [comment]
> After your closer look, do you mean that yours is much shorter?

Yes: it's basically just (3) followed by the `equiv-sym` of (3).

> Also, instead of just copying the proofs over to category, do you know if there is a better way (such as generalizing the proofs so that category and monoid are just instances of it)?

Oh, that's a good idea! Yes, I think it  should be possible. Let's see... I think the category version would be general enough, we can then specialize it to monoids by choosing `FreeCategory.Carrier.C = \_ _ -> FreeMonoid.Carrier.A`, and by wrapping all the relevant proofs with conversions to and from values which have the same structures but different names, such as `FreeCategory` and `List`.

**Comment by dimecon** [comment]
Ah, I see, thanks! I fixed the soundness proof. Moving the `FreeCategory` discussion to the other issue.
